/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fbf9f5",
        "surface-container-high": "#e9e8e3",
        "on-secondary-fixed": "#344429",
        "on-tertiary-fixed-variant": "#5b5972",
        "primary-fixed": "#feb294",
        "primary-dim": "#7c442d",
        "secondary-fixed-dim": "#c8dbb6",
        "surface-container": "#efeee9",
        "tertiary": "#5f5c75",
        "on-background": "#31332f",
        "tertiary-dim": "#535069",
        "error": "#a83836",
        "surface-dim": "#dadad4",
        "primary-container": "#feb294",
        "error-dim": "#67040d",
        "secondary": "#536446",
        "surface-tint": "#8a5038",
        "secondary-fixed": "#d6e9c3",
        "on-primary-container": "#63301b",
        "on-secondary": "#edffda",
        "on-surface": "#31332f",
        "secondary-dim": "#48583b",
        "on-surface-variant": "#5e605b",
        "on-tertiary": "#fcf7ff",
        "on-primary-fixed-variant": "#6d3923",
        "primary-fixed-dim": "#eea587",
        "on-error-container": "#6e0a12",
        "surface-container-highest": "#e3e3dc",
        "surface": "#fbf9f5",
        "outline": "#7a7b76",
        "tertiary-container": "#e3dffd",
        "tertiary-fixed-dim": "#d5d1ee",
        "on-secondary-container": "#46563a",
        "on-error": "#fff7f6",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d6e9c3",
        "outline-variant": "#b2b2ad",
        "inverse-on-surface": "#9e9d99",
        "on-secondary-fixed-variant": "#506043",
        "error-container": "#fa746f",
        "on-primary-fixed": "#491d09",
        "tertiary-fixed": "#e3dffd",
        "on-tertiary-container": "#514f67",
        "surface-container-low": "#f5f4ef",
        "surface-bright": "#fbf9f5",
        "inverse-primary": "#feb294",
        "on-tertiary-fixed": "#3f3d54",
        "inverse-surface": "#0e0e0d",
        "primary": "#8a5038",
        "on-primary": "#fff7f5",
        "surface-variant": "#e3e3dc"
      },
      fontFamily: {
        "headline": ["Noto Serif SC", "Georgia", "serif"],
        "body": ["Noto Serif SC", "Georgia", "serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
